module.exports = {
  personName: [
    {regex: /Dipl.-(Inf.|Ing.|Betriebsw.|Wirtsch.-Inf.|Soz.päd.) /g, replacement: ''},
    {regex: /Dipl.-(Agrar Ing.|Archivar|Betriebsw.|Bibl.|Bioinf.|Bioing.|Biomath.|Chem.|Des.|Dok.|Dolm.|Energiewirt|Ergotherapeut|oec.-troph.|Fachübersetzer|Finw.|Forsting.|Dipl. FÖ|Freizeitwiss.|Ges.oec.|Immobilienw.|Inf.|Inform.|Inf.-Wirt|Infw.|Ing.|Ing. Gartenbau|Journ.|Kffr.|Kfm.|Komm.Psych.|Kult.arb.|Künstler|Kunsttherap.|Logist.|Math.|Medieninform.|Medienök.|Medienw.|Mediator|Museol.|Musiktherap.|Naut.|Dipl.oec.troph|Online-Journalist|Pfl.|Pflegew.|Pflegepäd.|Physiotherapeut|Pol.|Red.|Rel.-päd.|Rest.|Reha-psych.|Rpfl.|Sicherheitsing.|Soz. Arb.|Soz.jur.|Soz.päd.|Soz.wirt|Techn.|Tech.-Red.|Übers.|Vers.-Betriebsw.|Verww.|Verw.-Betriebsw.|Verw.-Manager|Volksw.|Wirt.-Inf.|Wi.-Inform.|Wirtsch.-Ing.|Wirt.-Ing.|Wi.Jur.|Wirtschaftspsych.|Wirt.-Übers.) /g, replacement: ''},
    {regex: /Dipl.(-Anim.|-Arch.| Audiovisuelle Medien|-Des.|-Film- u. Fernsehdram.|-Film- u. Fernsehwirt.|-Filmkomp.| Freie Kunst|-Ing.|-Kam.| Kunstpädagogik| Kunstpädagogik\/Kunstvermittlung|-Kunst.-Päd.|-Rest.| Mus.|-Mus.-Päd.|-Musikl.|-Reg.|-Schau.|-Schnittm.|-Szeneb.|-Szenem.|-Tonm.| Vis. Komm.) /g, replacement: ''},
    {regex: /Dipl.(agr.biol.|agr.oec.|-Angl.|-Arch.|-Berufspäd.|-Betriebsw.|-Bibl.|-Biochem.|-Biogeogr.|-Bioinf.|-Biol.|-Biol. (t.o.)|-Biophys.|-Biotechnol.|-Braumeister|-Chem.|-Chem.-Ing.|-Chem.oec.|-Comp.-Math.|-Demogr.|-Des.|-Dolm.|-Dram.|-Forstw.|-Geogr.|-Geoinf.|-Geol.|-Geoökol.|-Geophys.|-Germ.|-Geront.|-Ges.oec.|-Ghl.| GDFS|-Gwl.|-Gyml.|-Hdl.|-Heilpäd.|-Hist.|-Holzwirt|-Humanbiologe| human. biol.|-Hydrol.|-Ind. Arch.|-Inf. oder -Inform.|-Inform. Med.|-Inf.Wirt\/Inform.Wirt|-Inf.wiss|-Ing.|-Ing. agr.|-Ing.-Inf.|-Ing. oec.|-Ing.-Päd.|-Ing. silv.|-jur. oder -Jur.|-Journ.|-Kff. oder -Kffr.|-Kfm.|-Kfm. t.o.|-Komm.-Wirt|-Krim.|-Krim.|-Kult.|-Kult.Päd.|-Kult.Man.|-Kulturwirt|-Künstler|-Kunstpädagoge|-Landsch.-ökol.|-Lebensmittelchem.|-Lehrer|-Ling.|-LMChem.|-LM-Ing.|-Logist.|-Math.|-Math. oec. oder -Wi.-Math. oder -Wirtschaftsmath. Univ.|-Math. techn.|-Med.|-Vet.-Med.|-Med. Päd.|-Medienberater|-Mediengestalter|-Medieninf.|-Medienprakt.|-Medienwirt|-Medienwiss.|-Met.|-Mot.|-Mol.Med.|-Mikrobiol.|-Mil.|-Min.|-NanoSc.|-Nat.|-Hist.Sc|-Neurowiss.|oec.troph.|-Oec.|-Ök.|-oen.|-Orient.|-Orientarchäologe|-Oz.|-Päd.|-Pfl.|-PGW|-Pharm.|-Phil.|-Phys.|-Phys. (Med.)|-Phys.Ing.|-Phys. oec.|-Pol.|-Prähist.|-Psych.|-Reg.-Wiss.|-Reh.-Päd.| rer. com.| rer. oec.| rer. pol.|-Rom.| sc. pol. Univ.|-Sicherheits.-Ing.|-Soz.Ök.|-Soz.|-Soz. tech.|-Soz.päd.|-Sozw.|-Sozialw.[30] oder -Soz.Wiss.|-Sporting.|-Sportl.|-SpOec.|-Sportwiss.|-Sprachm.|-Sprechwiss.|-Staatsw.[31]|-Stat.|-Stom.|-Stomat.|-Systemwiss.|-Tech. Math.|-Technoinform.|-Theol.|-Troph.|-Übersetzer|-Umweltwiss.|-UWT|-Verk.wirtsch.|-Verw. Wiss.|-Volksw.|-Wirt.|-Wirtchem.|-Wirt.-Inf.|-Wirt.-Inform.|-Wirtsch.-Inf.|-Wirtsch.Inf.|-Wirtsch.-Inform.|-Wi.-Ing.|-Wirt.-Ing.|-Wirtsch.-Ing.| iur .oec. univ.|-Wigeo.|-Wirtl.|-Wipäd.|-Wiss.org.|-WiWi.) /g, replacement: ''},
    {regex: /Dr.( agr.| B.A.\/D.B.A.| biol. anim.| biol. hom.| cult.| disc. pol.|-Ing.| iur.| iur. can.| iur. et rer. pol.| iur. utr.| math.| med.| med. dent.| med. sci.| med. vet.| nat. med.| nat. techn.| oec.| oec. publ.| oec. troph.| paed.| pharm.| phil.| phil. in art.| phil. nat.| PH| rer. agr.| rer. biol. hum.| rer. biol. vet.| rer. cult.| rer. cur.| rer. forest.| rer. hort.| rer. hum.| rer. med.| rer. medic.| rer. merc.| rer. mont.| rer. nat.| rer. oec.| rer. physiol.| rer. pol.| rer. publ.| rer. sec.| rer. silv.| rer. soc.| rer. sust.| rer. tech.| sc. agr.| sc. ed.| sc. hum.| sc. mus.| sc. oec.| sc. phil.| sc. pol.| sc. soc.| sc. techn.| Sportwiss.| theol.| troph.) /g, replacement: 'Dr. '},
  ],
  language: {
    'deu': 'de',
    'eng': 'en',
  },
  subjects: {
    'Geschichte': 'https://w3id.org/kim/hochschulfaechersystematik/n05',
    'Informatik': 'https://w3id.org/kim/hochschulfaechersystematik/n71',
    'Internationales Recht': 'https://w3id.org/kim/hochschulfaechersystematik/n28',
    'Mathematik': 'https://w3id.org/kim/hochschulfaechersystematik/n37'
  }
}
